import bcrypt from 'bcryptjs';
import { IUser, IWorker, ICategory, IService, IBooking, IReview, IComplaint, ICustomServiceRequest } from './types';

// Pre-hashed password for Demo passwords: "Admin@123", "Worker@123", "User@123"
// We'll compute sync hash or use bcrypt.hashSync
const HASHED_ADMIN = bcrypt.hashSync('Admin@123', 10);
const HASHED_WORKER = bcrypt.hashSync('Worker@123', 10);
const HASHED_USER = bcrypt.hashSync('User@123', 10);

export const initialCategories: ICategory[] = [
  {
    _id: 'cat-1',
    name: 'Plumbing',
    description: 'Pipe repair, faucet installation, drainage fixing, bathroom fitting & unclogging.',
    icon: 'Wrench',
    image: 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-2',
    name: 'Electrical',
    description: 'Short circuit fix, wiring, switchboards, MCB, meter repair & home lighting.',
    icon: 'Zap',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-3',
    name: 'AC Repair',
    description: 'Gas refill, deep servicing, cooling troubleshooting, installation & uninstallation.',
    icon: 'Wind',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-4',
    name: 'Fan Repair',
    description: 'Ceiling fan, exhaust fan, high-speed wall fan rewiring, capacitor replacement.',
    icon: 'Fan',
    image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-5',
    name: 'Water Leakage',
    description: 'Ceiling seepage detection, wall dampness repair, pipeline leak seal and waterproofing.',
    icon: 'Droplets',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-6',
    name: 'Motor Repair',
    description: 'Submersible motor, booster pump, capacitor, coil rewinding & pressure switch service.',
    icon: 'Gauge',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-7',
    name: 'Carpentry',
    description: 'Furniture repair, door lock installation, hinge fixing, modular kitchen assembly.',
    icon: 'Hammer',
    image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-8',
    name: 'Painting',
    description: 'Interior & exterior house painting, waterproof priming, texture wall design & touch-ups.',
    icon: 'Paintbrush',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-9',
    name: 'Appliance Repair',
    description: 'Microwave ovens, geysers, kitchen chimneys, induction cooktops, mixer grinders.',
    icon: 'Cpu',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-10',
    name: 'Washing Machine Repair',
    description: 'Front load & top load drum repair, water drain issue, spinning vibration, motherboard PCB.',
    icon: 'Disc',
    image: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-11',
    name: 'Refrigerator Repair',
    description: 'Single/Double door frost free, compressor check, thermostat sensor, rubber gasket replace.',
    icon: 'Box',
    image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-12',
    name: 'RO / Water Purifier Repair',
    description: 'Filter replacement, membrane cleaning, TDS balancing, pump repair, leaking pipe fix.',
    icon: 'Filter',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-13',
    name: 'TV Repair',
    description: 'LED, LCD, OLED display panel repair, backlight replacement, HDMI & sound card fix.',
    icon: 'Tv',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-14',
    name: 'Cleaning Services',
    description: 'Full home deep cleaning, bathroom sanitization, sofa shampooing, kitchen chimney degrease.',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
  {
    _id: 'cat-15',
    name: 'Pest Control',
    description: 'Cockroach herbal gel, termite eradication, bed bug treatment, mosquito fogging.',
    icon: 'ShieldAlert',
    image: 'https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&w=600&q=80',
    status: 'Active',
    createdAt: new Date('2025-01-01').toISOString(),
  },
];

export const initialServices: IService[] = [
  { _id: 'srv-1', name: 'Tap & Faucet Leak Repair', category: 'Plumbing', description: 'Fix leaking taps, bib cocks, and spout joints.', basePrice: 249, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-2', name: 'Drainage Pipe Unclogging', category: 'Plumbing', description: 'Remove blockages from kitchen sink or bathroom drain.', basePrice: 499, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-3', name: 'Switchboard & Socket Installation', category: 'Electrical', description: 'Fix burnt switches or wire new modular sockets.', basePrice: 199, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-4', name: 'MCB Tripping Troubleshooting', category: 'Electrical', description: 'Diagnose home short circuit and balance load on MCB.', basePrice: 399, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-5', name: 'Split AC Deep Foam Jet Servicing', category: 'AC Repair', description: 'Comprehensive indoor and outdoor unit jet cleaning.', basePrice: 599, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-6', name: 'AC Gas Charging & Leak Fix', category: 'AC Repair', description: 'R32 / R410 refrigerant refill with pressure testing.', basePrice: 1899, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-7', name: 'Ceiling Fan Installation & Repair', category: 'Fan Repair', description: 'Bearing replacement, speed regulator & hanging setup.', basePrice: 249, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-8', name: 'Bathroom Seepage Water Proofing', category: 'Water Leakage', description: 'Chemical injection grouting to stop bathroom leaks.', basePrice: 1499, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-9', name: 'Water Pump Motor Rewinding', category: 'Motor Repair', description: 'Copper winding replacement for water booster motors.', basePrice: 1199, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-10', name: 'Door Lock & Handle Fitting', category: 'Carpentry', description: 'Install high-security mortise lock or cylinder replacement.', basePrice: 349, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-11', name: 'Modular Wardrobe Hinge Repair', category: 'Carpentry', description: 'Adjust or replace hydraulic soft-close cabinet hinges.', basePrice: 299, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-12', name: 'Single Room Wall Painting & Touch-up', category: 'Painting', description: 'Emulsion paint application with putty sanding.', basePrice: 2499, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-13', name: 'Microwave Heating Diagnosis', category: 'Appliance Repair', description: 'Magnetron and high-voltage capacitor testing.', basePrice: 449, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-14', name: 'Washing Machine Drum & Spin Repair', category: 'Washing Machine Repair', description: 'Fix noise, belt slippage, and drain pump errors.', basePrice: 699, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-15', name: 'Refrigerator Cooling & Gas Check', category: 'Refrigerator Repair', description: 'Compressor relay and thermostat replacement.', basePrice: 799, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-16', name: 'RO Filter & Sediment Membrane Service', category: 'RO / Water Purifier Repair', description: 'Replace pre-carbon filter and check TDS ppm level.', basePrice: 649, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-17', name: 'LED TV Backlight & Sound Repair', category: 'TV Repair', description: 'Replace LED strips and resolve display distortion.', basePrice: 999, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-18', name: 'Complete 2BHK Deep Sanitization', category: 'Cleaning Services', description: 'Kitchen, bathroom, floor buffing & balcony wash.', basePrice: 2999, status: 'Active', createdAt: new Date().toISOString() },
  { _id: 'srv-19', name: 'Odorless Cockroach Pest Treatment', category: 'Pest Control', description: 'Commercial grade gel application in cabinets & sinks.', basePrice: 899, status: 'Active', createdAt: new Date().toISOString() },
];

export const initialUsers: IUser[] = [
  // Admin Demo
  {
    _id: 'usr-admin',
    name: 'HomeAssist Admin',
    email: 'admin@homeassist.demo',
    phone: '+91 98765 43210',
    password: HASHED_ADMIN,
    role: 'admin',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    address: 'HQ Tower 4, Tech Park',
    city: 'Bangalore',
    area: 'Indiranagar',
    bio: 'Lead platform administrator for HomeAssist network.',
    status: 'Active',
    createdAt: new Date('2024-12-01').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Worker Demo
  {
    _id: 'usr-worker-demo',
    name: 'Ramesh Patel',
    email: 'worker@homeassist.demo',
    phone: '+91 98111 22334',
    password: HASHED_WORKER,
    role: 'worker',
    profileImage: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=400&q=80',
    address: '14th Cross, 2nd Main, Koramangala',
    city: 'Bangalore',
    area: 'Koramangala',
    bio: 'Master certified technician with 8+ years experience in electrical wiring, AC cooling & MCB systems.',
    status: 'Active',
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Customer Demo
  {
    _id: 'usr-customer-demo',
    name: 'Rahul Sharma',
    email: 'user@homeassist.demo',
    phone: '+91 98222 33445',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    address: 'Apartment 304, Green Glen Layout, Bellandur',
    city: 'Bangalore',
    area: 'Bellandur',
    bio: 'Software engineer who loves smart home maintenance and reliable trusted local pros.',
    status: 'Active',
    createdAt: new Date('2025-01-15').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // 9 Additional realistic customer users
  {
    _id: 'usr-cust-2',
    name: 'Priya Reddy',
    email: 'priya.reddy@example.com',
    phone: '+91 98333 44556',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    address: 'Villa 12, Palm Meadows',
    city: 'Bangalore',
    area: 'Whitefield',
    bio: 'Architect passionate about sustainable interiors and clean fixtures.',
    status: 'Active',
    createdAt: new Date('2025-01-18').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'usr-cust-3',
    name: 'Arjun Kumar',
    email: 'arjun.k@example.com',
    phone: '+91 98444 55667',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    address: 'Flat 8B, Skylark Enclave',
    city: 'Bangalore',
    area: 'HSR Layout',
    bio: 'Product manager and fitness enthusiast.',
    status: 'Active',
    createdAt: new Date('2025-01-20').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'usr-cust-4',
    name: 'Sneha Rao',
    email: 'sneha.rao@example.com',
    phone: '+91 98555 66778',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    address: 'House 45, 5th Block',
    city: 'Bangalore',
    area: 'Jayanagar',
    bio: 'Educator and gardening lover.',
    status: 'Active',
    createdAt: new Date('2025-01-22').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'usr-cust-5',
    name: 'Kiran Kumar',
    email: 'kiran.kumar@example.com',
    phone: '+91 98666 77889',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
    address: 'Tower C-102, Prestige Shantiniketan',
    city: 'Bangalore',
    area: 'Whitefield',
    bio: 'Frequent traveler who relies on verified workers for rapid repairs.',
    status: 'Active',
    createdAt: new Date('2025-01-25').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'usr-cust-6',
    name: 'Ananya Singh',
    email: 'ananya.singh@example.com',
    phone: '+91 98777 88990',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    address: '601 Marvel Residency',
    city: 'Bangalore',
    area: 'Indiranagar',
    bio: 'Graphic designer and pet owner.',
    status: 'Active',
    createdAt: new Date('2025-01-28').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'usr-cust-7',
    name: 'Rohit Verma',
    email: 'rohit.verma@example.com',
    phone: '+91 98888 99001',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    address: '22 BDA Layout',
    city: 'Bangalore',
    area: 'BTM Layout',
    bio: 'Startup founder and coffee addict.',
    status: 'Active',
    createdAt: new Date('2025-02-01').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'usr-cust-8',
    name: 'Neha Reddy',
    email: 'neha.reddy@example.com',
    phone: '+91 98999 00112',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    address: 'Apt 1204, Salarpuria Sattva',
    city: 'Bangalore',
    area: 'Marathahalli',
    bio: 'Content strategist and home baker.',
    status: 'Active',
    createdAt: new Date('2025-02-03').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'usr-cust-9',
    name: 'Vivek Sharma',
    email: 'vivek.s@example.com',
    phone: '+91 98123 45678',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    address: '304 Silver Springs',
    city: 'Bangalore',
    area: 'Electronic City',
    bio: 'Civil engineer and DIY enthusiast.',
    status: 'Active',
    createdAt: new Date('2025-02-05').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'usr-cust-10',
    name: 'Pooja Nair',
    email: 'pooja.nair@example.com',
    phone: '+91 98234 56789',
    password: HASHED_USER,
    role: 'user',
    profileImage: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    address: 'House 89, 7th Cross',
    city: 'Bangalore',
    area: 'JP Nagar',
    bio: 'Music teacher and mother of two.',
    status: 'Active',
    createdAt: new Date('2025-02-08').toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Additional workers for realistic database seeding
export const initialWorkers: IWorker[] = [
  // Demo Worker linked to usr-worker-demo
  {
    _id: 'wrk-demo',
    user: 'usr-worker-demo',
    name: 'Ramesh Patel',
    email: 'worker@homeassist.demo',
    phone: '+91 98111 22334',
    profession: 'Senior Electrician & AC Specialist',
    services: ['Electrical', 'AC Repair', 'Fan Repair'],
    experience: 8,
    skills: ['MCB Wiring', 'Inverter Setup', 'AC Gas Refill', 'Modular Board Assembly', 'Ceiling Fan Rewinding'],
    about: 'Government certified master electrician with 8+ years hands-on field experience. Fast diagnosis, transparent pricing, and 30-day service warranty on all electrical and AC repairs.',
    serviceArea: 'Koramangala, HSR Layout, BTM, Bellandur',
    city: 'Bangalore',
    address: '14th Cross, 2nd Main, Koramangala',
    location: {
      lat: 12.9352,
      lng: 77.6245,
      addressText: 'Koramangala 4th Block, Bangalore',
    },
    availability: 'Available',
    rating: 4.9,
    totalReviews: 48,
    completedJobs: 132,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 350,
    joinedDate: '2024-11-12',
    createdAt: new Date('2024-11-12').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'wrk-2',
    user: 'usr-wrk-2',
    name: 'Suresh Kumar',
    email: 'suresh.plumbing@example.com',
    phone: '+91 97222 33441',
    profession: 'Master Plumber & Seepage Expert',
    services: ['Plumbing', 'Water Leakage', 'Motor Repair'],
    experience: 11,
    skills: ['Concealed Pipe Detection', 'Bathroom Fittings', 'Drain Jetting', 'Overhead Tank Connection', 'Waterproofing'],
    about: 'Over a decade fixing high-pressure commercial and residential plumbing issues. Specializing in wall leakage inspection without unnecessary drilling.',
    serviceArea: 'Indiranagar, Domlur, Ulsoor, MG Road',
    city: 'Bangalore',
    address: '100 Feet Rd, Indiranagar',
    location: {
      lat: 12.9784,
      lng: 77.6408,
      addressText: '100 Feet Rd, Indiranagar, Bangalore',
    },
    availability: 'Available',
    rating: 4.8,
    totalReviews: 64,
    completedJobs: 189,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 300,
    joinedDate: '2024-09-15',
    createdAt: new Date('2024-09-15').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'wrk-3',
    user: 'usr-wrk-3',
    name: 'Vikram Jadhav',
    email: 'vikram.ac@example.com',
    phone: '+91 97333 44552',
    profession: 'Certified HVAC & AC Technician',
    services: ['AC Repair', 'Refrigerator Repair'],
    experience: 7,
    skills: ['Copper Brazing', 'PCB Diagnostics', 'Inverter AC Troubleshooting', 'Compressor Rebuilding'],
    about: 'Expert in multi-brand split and window air conditioners. Providing genuine parts, leak inspection, and rapid 60-minute emergency cooling repair.',
    serviceArea: 'HSR Layout, Sarjapur Road, Bellandur',
    city: 'Bangalore',
    address: 'Sector 3, HSR Layout',
    location: {
      lat: 12.9121,
      lng: 77.6446,
      addressText: 'Sector 3, HSR Layout, Bangalore',
    },
    availability: 'Available',
    rating: 4.9,
    totalReviews: 52,
    completedJobs: 147,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 400,
    joinedDate: '2024-10-01',
    createdAt: new Date('2024-10-01').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'wrk-4',
    user: 'usr-wrk-4',
    name: 'Manohar Lal Sharma',
    email: 'manohar.carpenter@example.com',
    phone: '+91 97444 55663',
    profession: 'Custom Furniture & Master Carpenter',
    services: ['Carpentry'],
    experience: 14,
    skills: ['Door Fitting', 'Modular Kitchen Hinge Replacement', 'Wood Polishing', 'Balcony Wardrobe Assembly'],
    about: 'Generational carpenter with meticulous eye for detail. From stubborn sliding door tracks to custom teak wood repairs and lock changes.',
    serviceArea: 'Jayanagar, JP Nagar, Banashankari',
    city: 'Bangalore',
    address: '4th Block, Jayanagar',
    location: {
      lat: 12.9308,
      lng: 77.5838,
      addressText: '4th Block, Jayanagar, Bangalore',
    },
    availability: 'Available',
    rating: 4.7,
    totalReviews: 39,
    completedJobs: 110,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 350,
    joinedDate: '2024-08-20',
    createdAt: new Date('2024-08-20').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'wrk-5',
    user: 'usr-wrk-5',
    name: 'Rajesh Naidu',
    email: 'rajesh.appliances@example.com',
    phone: '+91 97555 66774',
    profession: 'Home Appliance & Washing Machine Tech',
    services: ['Washing Machine Repair', 'Refrigerator Repair', 'Appliance Repair'],
    experience: 9,
    skills: ['Front Load PCB Diagnostics', 'Motor Belt Calibration', 'Thermostat Sensor Testing', 'Microwave Magnetron'],
    about: 'Specialist for Bosch, Samsung, LG and IFB domestic appliances. Rapid on-site diagnostics with genuine manufacturer components.',
    serviceArea: 'Whitefield, Marathahalli, Varthur',
    city: 'Bangalore',
    address: 'ITPL Main Road, Whitefield',
    location: {
      lat: 12.9698,
      lng: 77.7499,
      addressText: 'ITPL Main Road, Whitefield, Bangalore',
    },
    availability: 'Available',
    rating: 4.8,
    totalReviews: 44,
    completedJobs: 126,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 320,
    joinedDate: '2024-11-05',
    createdAt: new Date('2024-11-05').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'wrk-6',
    user: 'usr-wrk-6',
    name: 'Maheshwari & Sons Painting',
    email: 'mahesh.painter@example.com',
    phone: '+91 97666 77885',
    profession: 'Wall Painter & Waterproofing Specialist',
    services: ['Painting', 'Water Leakage'],
    experience: 12,
    skills: ['Damp Proofing', 'Royal Luxury Emulsion', 'Texture Paint', 'Exterior Weathercoat', 'Wood Staining'],
    about: 'Professional home painting crew offering zero-mess masking, high-speed motorized roller work, and guaranteed anti-fungal paint warranties.',
    serviceArea: 'Electronic City, BTM, Bannerghatta Road',
    city: 'Bangalore',
    address: 'Phase 1, Electronic City',
    location: {
      lat: 12.8452,
      lng: 77.6602,
      addressText: 'Phase 1, Electronic City, Bangalore',
    },
    availability: 'Available',
    rating: 4.9,
    totalReviews: 58,
    completedJobs: 165,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 450,
    joinedDate: '2024-07-10',
    createdAt: new Date('2024-07-10').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'wrk-7',
    user: 'usr-wrk-7',
    name: 'Anil Chander',
    email: 'anil.ro@example.com',
    phone: '+91 97777 88996',
    profession: 'Water Purifier & RO Specialist',
    services: ['RO / Water Purifier Repair', 'Plumbing'],
    experience: 6,
    skills: ['TDS Balancing', 'RO Membrane Replacement', 'UV Lamp Fix', 'Booster Pump Service', 'Pre-Filter Housing'],
    about: 'Pure drinking water is vital for family health. I test water TDS before and after service, using only certified food-grade replacement filters.',
    serviceArea: 'Malleshwaram, Rajajinagar, Yeshwanthpur',
    city: 'Bangalore',
    address: 'Sampige Road, Malleshwaram',
    location: {
      lat: 13.0031,
      lng: 77.5643,
      addressText: 'Sampige Road, Malleshwaram, Bangalore',
    },
    availability: 'Available',
    rating: 4.8,
    totalReviews: 31,
    completedJobs: 92,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 280,
    joinedDate: '2024-12-01',
    createdAt: new Date('2024-12-01').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'wrk-8',
    user: 'usr-wrk-8',
    name: 'Ganesh Shinde',
    email: 'ganesh.tv@example.com',
    phone: '+91 97888 99007',
    profession: 'Smart TV & Audio Equipment Tech',
    services: ['TV Repair', 'Appliance Repair'],
    experience: 8,
    skills: ['LED Backlight Repair', 'Screen Inverter Fix', 'Mainboard Flashing', 'HDMI Port Replacement'],
    about: 'Dedicated television repair professional. We repair damaged backlight rows on same-day basis with genuine LED chips and provide warranty.',
    serviceArea: 'Koramangala, Indiranagar, HSR Layout',
    city: 'Bangalore',
    address: '80 Feet Road, Koramangala',
    location: {
      lat: 12.9345,
      lng: 77.6200,
      addressText: '80 Feet Road, Koramangala, Bangalore',
    },
    availability: 'Available',
    rating: 4.7,
    totalReviews: 29,
    completedJobs: 78,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 350,
    joinedDate: '2024-10-18',
    createdAt: new Date('2024-10-18').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'wrk-9',
    user: 'usr-wrk-9',
    name: 'CleanPro Deep Cleaning Crew',
    email: 'cleanpro@example.com',
    phone: '+91 97999 00118',
    profession: 'Home Sanitization & Cleaning Supervisor',
    services: ['Cleaning Services'],
    experience: 5,
    skills: ['Single Disk Scrubbing', 'Sofa Deep Shampooing', 'Bathroom Descaling', 'Kitchen Degreasing'],
    about: 'Trained professional cleaning staff equipped with industrial Karcher vacuum cleaners and German eco-friendly cleaning detergents.',
    serviceArea: 'Bellandur, Sarjapur, Whitefield, HSR',
    city: 'Bangalore',
    address: 'Outer Ring Road, Bellandur',
    location: {
      lat: 12.9260,
      lng: 77.6762,
      addressText: 'Outer Ring Road, Bellandur, Bangalore',
    },
    availability: 'Available',
    rating: 4.9,
    totalReviews: 76,
    completedJobs: 215,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 500,
    joinedDate: '2024-06-15',
    createdAt: new Date('2024-06-15').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'wrk-10',
    user: 'usr-wrk-10',
    name: 'SafeShield Pest Solutions',
    email: 'safeshield@example.com',
    phone: '+91 98111 99223',
    profession: 'Government Licensed Pest Controller',
    services: ['Pest Control'],
    experience: 10,
    skills: ['Odorless Cockroach Gel', 'Drill-Fill-Seal Termite Barrier', 'Bed Bug Heat Treatment', 'Rodent Baiting'],
    about: 'Certified pest eradication services with 100% human-safe, pet-friendly certified bio-chemicals. Comes with 60-day re-treatment guarantee.',
    serviceArea: 'All Bangalore Central & Suburbs',
    city: 'Bangalore',
    address: 'Residency Road, Ashok Nagar',
    location: {
      lat: 12.9698,
      lng: 77.6000,
      addressText: 'Residency Road, Bangalore',
    },
    availability: 'Available',
    rating: 4.8,
    totalReviews: 49,
    completedJobs: 138,
    verificationStatus: 'Verified',
    status: 'Approved',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 400,
    joinedDate: '2024-08-01',
    createdAt: new Date('2024-08-01').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pending Approval Worker (Crucial for Admin testing!)
  {
    _id: 'wrk-pending-1',
    user: 'usr-wrk-p1',
    name: 'Santosh Gowda',
    email: 'santosh.plumber@example.com',
    phone: '+91 98333 11223',
    profession: 'Residential Plumber & Sanitary Fitter',
    services: ['Plumbing', 'Water Leakage'],
    experience: 4,
    skills: ['PVC Pipe Fitting', 'Basin Replacement', 'Clogged Toilet Repair'],
    about: 'Skilled plumber with 4 years experience working in apartment complexes. Applying to join HomeAssist network.',
    serviceArea: 'Hebbal, Yelahanka, RT Nagar',
    city: 'Bangalore',
    address: 'Near Hebbal Flyover',
    location: {
      lat: 13.0358,
      lng: 77.5970,
      addressText: 'Hebbal, Bangalore',
    },
    availability: 'Available',
    rating: 0,
    totalReviews: 0,
    completedJobs: 0,
    verificationStatus: 'Unverified',
    status: 'Pending',
    profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 250,
    joinedDate: '2025-02-14',
    createdAt: new Date('2025-02-14').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Another Pending Worker for Admin approval testing
  {
    _id: 'wrk-pending-2',
    user: 'usr-wrk-p2',
    name: 'Farhan Akhtar',
    email: 'farhan.motor@example.com',
    phone: '+91 98444 22334',
    profession: 'Heavy Motor Rewinding & Pump Technician',
    services: ['Motor Repair', 'Electrical'],
    experience: 7,
    skills: ['Borewell Pump Diagnosis', 'Submersible Motor Seal', 'Copper Winding'],
    about: 'Specialized in multi-stage booster pumps and overhead tank automatic sensor switches.',
    serviceArea: 'Kengeri, Rajarajeshwari Nagar',
    city: 'Bangalore',
    address: 'RR Nagar Main Road',
    location: {
      lat: 12.9237,
      lng: 77.5186,
      addressText: 'RR Nagar, Bangalore',
    },
    availability: 'Available',
    rating: 0,
    totalReviews: 0,
    completedJobs: 0,
    verificationStatus: 'Unverified',
    status: 'Pending',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    hourlyRate: 350,
    joinedDate: '2025-02-16',
    createdAt: new Date('2025-02-16').toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialBookings: IBooking[] = [
  {
    _id: 'bkg-101',
    bookingNumber: 'HA-2025-0101',
    customer: 'usr-customer-demo',
    worker: 'wrk-demo',
    service: 'AC Gas Charging & Leak Fix',
    date: '2025-02-10',
    time: '11:00 AM',
    description: 'Master bedroom split AC is blowing warm air and showing error code E4. Needs leak check and gas refilling.',
    location: {
      address: 'Apartment 304, Green Glen Layout',
      city: 'Bangalore',
      area: 'Bellandur',
      lat: 12.9260,
      lng: 77.6762,
    },
    bookingStatus: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'Mock UPI',
    amount: 1899,
    workerNotes: 'Pressure tested copper joints, fixed micro flare leak, vacuumed and refilled 750g R32 gas. Cooling restored to 18°C.',
    createdAt: new Date('2025-02-09T10:00:00Z').toISOString(),
    updatedAt: new Date('2025-02-10T12:30:00Z').toISOString(),
  },
  {
    _id: 'bkg-102',
    bookingNumber: 'HA-2025-0102',
    customer: 'usr-customer-demo',
    worker: 'wrk-2',
    service: 'Tap & Faucet Leak Repair',
    date: '2025-02-18',
    time: '03:00 PM',
    description: 'Kitchen sink tap dripping constantly. Water puddle forming under the modular cabinet.',
    location: {
      address: 'Apartment 304, Green Glen Layout',
      city: 'Bangalore',
      area: 'Bellandur',
      lat: 12.9260,
      lng: 77.6762,
    },
    bookingStatus: 'Accepted',
    paymentStatus: 'COD',
    paymentMethod: 'COD',
    amount: 249,
    createdAt: new Date('2025-02-17T09:15:00Z').toISOString(),
    updatedAt: new Date('2025-02-17T11:00:00Z').toISOString(),
  },
  {
    _id: 'bkg-103',
    bookingNumber: 'HA-2025-0103',
    customer: 'usr-cust-2',
    worker: 'wrk-demo',
    service: 'MCB Tripping Troubleshooting',
    date: '2025-02-20',
    time: '10:30 AM',
    description: 'Main 32A MCB trips every time the water heater and microwave are switched on simultaneously.',
    location: {
      address: 'Villa 12, Palm Meadows',
      city: 'Bangalore',
      area: 'Whitefield',
      lat: 12.9698,
      lng: 77.7499,
    },
    bookingStatus: 'Pending',
    paymentStatus: 'Pending',
    paymentMethod: 'COD',
    amount: 399,
    createdAt: new Date('2025-02-19T08:30:00Z').toISOString(),
    updatedAt: new Date('2025-02-19T08:30:00Z').toISOString(),
  },
  {
    _id: 'bkg-104',
    bookingNumber: 'HA-2025-0104',
    customer: 'usr-cust-3',
    worker: 'wrk-4',
    service: 'Door Lock & Handle Fitting',
    date: '2025-02-05',
    time: '04:00 PM',
    description: 'Main balcony glass door lock latch stuck, cannot close securely.',
    location: {
      address: 'Flat 8B, Skylark Enclave',
      city: 'Bangalore',
      area: 'HSR Layout',
      lat: 12.9121,
      lng: 77.6446,
    },
    bookingStatus: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'Mock UPI',
    amount: 349,
    createdAt: new Date('2025-02-04T14:00:00Z').toISOString(),
    updatedAt: new Date('2025-02-05T17:00:00Z').toISOString(),
  },
];

export const initialReviews: IReview[] = [
  {
    _id: 'rev-1',
    customer: 'usr-customer-demo',
    worker: 'wrk-demo',
    booking: 'bkg-101',
    rating: 5,
    comment: 'Ramesh was extremely prompt and professional! Found the AC leak within 10 minutes and had all proper digital pressure gauges. Cooling is back to icy perfection. Highly recommended!',
    createdAt: new Date('2025-02-10T14:00:00Z').toISOString(),
  },
  {
    _id: 'rev-2',
    customer: 'usr-cust-3',
    worker: 'wrk-4',
    booking: 'bkg-104',
    rating: 5,
    comment: 'Manohar ji is a true craftsman. Fixed our balcony door lock quickly without damaging the wooden frame. Very polite and reasonably priced.',
    createdAt: new Date('2025-02-05T18:00:00Z').toISOString(),
  },
  {
    _id: 'rev-3',
    customer: 'usr-cust-4',
    worker: 'wrk-2',
    booking: 'bkg-101',
    rating: 5,
    comment: 'Solved a dampness problem that two previous plumbers failed to diagnose. Suresh is very honest and professional.',
    createdAt: new Date('2025-01-25T11:00:00Z').toISOString(),
  },
  {
    _id: 'rev-4',
    customer: 'usr-cust-5',
    worker: 'wrk-3',
    booking: 'bkg-101',
    rating: 4,
    comment: 'Good service for split AC filter and jet cleaning. Arrived on time with proper drop cloths to prevent water stains on walls.',
    createdAt: new Date('2025-01-29T16:00:00Z').toISOString(),
  },
];

export const initialComplaints: IComplaint[] = [
  {
    _id: 'cmp-1',
    customer: 'usr-cust-6',
    worker: 'wrk-demo',
    booking: 'bkg-101',
    title: 'Delay in arrival by 40 minutes due to rain',
    description: 'Technician was delayed due to heavy rain. Was updated on call but would appreciate more accurate arrival alerts.',
    status: 'Resolved',
    adminResponse: 'We have updated technician transit allowance and notified the team. The customer was issued a ₹100 platform discount token.',
    createdAt: new Date('2025-02-02T10:00:00Z').toISOString(),
    updatedAt: new Date('2025-02-03T11:00:00Z').toISOString(),
  },
  {
    _id: 'cmp-2',
    customer: 'usr-cust-7',
    title: 'Inquiry regarding warranty coverage for water pump',
    description: 'Wanted clarification on whether the 30-day warranty covers motor capacitor burnouts if there is a voltage spike.',
    status: 'Under Review',
    adminResponse: 'Support supervisor is reviewing warranty terms with the authorized vendor.',
    createdAt: new Date('2025-02-15T09:00:00Z').toISOString(),
    updatedAt: new Date('2025-02-15T12:00:00Z').toISOString(),
  },
];

export const initialCustomServices: ICustomServiceRequest[] = [
  {
    _id: 'csr-1',
    customer: 'usr-customer-demo',
    title: 'Digital Smart Door Lock Installation',
    description: 'Need installation of a Yale biometric fingerprint & PIN digital lock on 38mm solid teak front door. Requires precision mortise routing.',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    preferredDate: '2025-02-28',
    preferredTime: '02:00 PM',
    location: {
      address: 'Apartment 304, Green Glen Layout',
      city: 'Bangalore',
      area: 'Bellandur',
    },
    status: 'Approved',
    adminNotes: 'Assigned category Carpentry/Locksmith. Verified pro with specialized router notified.',
    createdAt: new Date('2025-02-12T14:30:00Z').toISOString(),
    updatedAt: new Date('2025-02-13T10:00:00Z').toISOString(),
  },
  {
    _id: 'csr-2',
    customer: 'usr-cust-8',
    title: 'Balcony Bird Netting Installation',
    description: 'Require heavy-duty nylon bird safety netting on 12ft x 8ft high-rise balcony to prevent pigeons.',
    preferredDate: '2025-03-02',
    preferredTime: '11:00 AM',
    location: {
      address: 'Apt 1204, Salarpuria Sattva',
      city: 'Bangalore',
      area: 'Marathahalli',
    },
    status: 'Pending',
    createdAt: new Date('2025-02-17T16:00:00Z').toISOString(),
    updatedAt: new Date('2025-02-17T16:00:00Z').toISOString(),
  },
];
